name: Docker

on:
  push:
    tags: 
      - '*'
jobs:

  build:
    name: Release Docker Image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Release
      run: make release
